import {
  Character,
  Rank,
  StatMod,
} from '../character-details/character-details.component';

export const characterList: Character[] = [
  {
    img: 'Akumu.PNG',
    name: 'Akumu',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Bucklolo.PNG',
    name: 'Bucklolo',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Bulolo.PNG',
    name: 'Bulolo',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Curoro.PNG',
    name: 'Curoro',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Dalalu.PNG',
    name: 'Dalalu',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Dangaga.PNG',
    name: 'Dangaga',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Deromo.PNG',
    name: 'Deromo',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Gadodo.PNG',
    name: 'Gadodo',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Gosusu.PNG',
    name: 'Gosusu',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Grahm.PNG',
    name: 'Grahm',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Grododu.PNG',
    name: 'Grododu',
    description: '',
    ability: {
      name: 'Genius',
      description: '',
      statAffecting: 'intelligence',
      statValue: 1,
      statModifier: StatMod.ADD,
    },
    weakness: {
      name: 'Disfigured',
      description: '',
      statAffecting: 'dexterity',
      statValue: 1,
      statModifier: StatMod.SUBTRACT,
    },
    stats: {
      strength: 2,
      dexterity: 2,
      constitution: 3,
      intelligence: 6,
      wisdom: 4,
      charisma: 3,
      luck: 5,
    },
    age: 0,
    height: 50,
    rank: Rank.CORPORAL,
  },
  {
    img: 'Hitoto.PNG',
    name: 'Hitoto',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Jamimi.PNG',
    name: 'Jamimi',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Jomara.PNG',
    name: 'Jomara',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Keroro.PNG',
    name: 'Keroro',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Kiki.PNG',
    name: 'Kiki',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Knightenbottom.PNG',
    name: 'Knightenbottom',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Kujijil.PNG',
    name: 'Kujijil',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Kyohehe.PNG',
    name: 'Kyohehe',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Lyudidi.PNG',
    name: 'Lyudidi',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Murama.PNG',
    name: 'Murama',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Murara.PNG',
    name: 'Murara',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Nanami.PNG',
    name: 'Nanami',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Nenamo.PNG',
    name: 'Nenamo',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Rizizu.PNG',
    name: 'Rizizu',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Romeme.PNG',
    name: 'Romeme',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Ronana.PNG',
    name: 'Ronana',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Scototo.PNG',
    name: 'Scototo',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Shadudu.PNG',
    name: 'Shadudu',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Shibibi.PNG',
    name: 'Shibibi',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Tenbu.PNG',
    name: 'Tenbu',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Teruru.PNG',
    name: 'Teruru',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Tikoko.PNG',
    name: 'Tikoko',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Ulerara.PNG',
    name: 'Ulerara',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Usagi.PNG',
    name: 'Usagi',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Xenono.PNG',
    name: 'Xenono',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Xi.PNG',
    name: 'Xi',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Yamoro.PNG',
    name: 'Yamoro',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Yonana.PNG',
    name: 'Yonana',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Yotaku.PNG',
    name: 'Yotaku',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
  {
    img: 'Zyena.PNG',
    name: 'Zyena',
    description: '',
    stats: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
      luck: 0,
    },
    age: 0,
    height: 0,
    rank: Rank.PRIVATE,
  },
];
